<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $now = now();

        $accounts = [
            // --- Bank accounts ---
            [
                'code' => 'ACCT-SONALI-001',
                'swift_code' => 'BSONBDDH',
                'name' => 'Sonali Bank PLC',
                'account_name' => 'Ops Account',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000001',
                'bank_name' => 'Sonali Bank PLC',
                'bank_routing_number' => '090100001',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Primary ops account.',
            ],
            [
                'code' => 'ACCT-JANATA-001',
                'swift_code' => 'JANBBDDH',
                'name' => 'Janata Bank PLC',
                'account_name' => 'Salary Account',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000002',
                'bank_name' => 'Janata Bank PLC',
                'bank_routing_number' => '090100002',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Payroll disbursement.',
            ],
            [
                'code' => 'ACCT-AGRANI-001',
                'swift_code' => 'AGRNBDDH',
                'name' => 'Agrani Bank PLC',
                'account_name' => 'Vendor Payments',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000003',
                'bank_name' => 'Agrani Bank PLC',
                'bank_routing_number' => '090100003',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'AP/Payouts.',
            ],
            [
                'code' => 'ACCT-RUPALI-001',
                'swift_code' => 'RUPBBDDH',
                'name' => 'Rupali Bank PLC',
                'account_name' => 'Collections',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000004',
                'bank_name' => 'Rupali Bank PLC',
                'bank_routing_number' => '090100004',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Incoming receipts.',
            ],
            [
                'code' => 'ACCT-BRAC-001',
                'swift_code' => 'BRAKBDDH',
                'name' => 'BRAC Bank PLC',
                'account_name' => 'Reserve',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000005',
                'bank_name' => 'BRAC Bank PLC',
                'bank_routing_number' => '095000001',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Cash reserve.',
            ],
            [
                'code' => 'ACCT-DBBL-001',
                'swift_code' => 'DBBLBDDH',
                'name' => 'Dutch-Bangla Bank PLC',
                'account_name' => 'Ops 2',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000006',
                'bank_name' => 'Dutch-Bangla Bank PLC',
                'bank_routing_number' => '095000002',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Secondary ops account.',
            ],
            [
                'code' => 'ACCT-CITY-001',
                'swift_code' => 'CIBLBDDH',
                'name' => 'The City Bank PLC',
                'account_name' => 'Settlements',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000007',
                'bank_name' => 'The City Bank PLC',
                'bank_routing_number' => '095000003',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Settlement account.',
            ],
            [
                'code' => 'ACCT-EBL-001',
                'swift_code' => 'EBLDBDDH',
                'name' => 'Eastern Bank PLC',
                'account_name' => 'Refunds',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000008',
                'bank_name' => 'Eastern Bank PLC',
                'bank_routing_number' => '095000004',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Customer refunds.',
            ],
            [
                'code' => 'ACCT-PRIME-001',
                'swift_code' => 'PRBLBDDH',
                'name' => 'Prime Bank PLC',
                'account_name' => 'Treasury',
                'is_active' => true,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000009',
                'bank_name' => 'Prime Bank PLC',
                'bank_routing_number' => '095000005',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Treasury ops.',
            ],
            [
                'code' => 'ACCT-ABBL-001',
                'swift_code' => 'ABBLBDDH',
                'name' => 'AB Bank PLC',
                'account_name' => 'Compliance Reserve',
                'is_active' => false,
                'type' => 'bank',
                'card_type' => null,
                'account_number' => '100000000010',
                'bank_name' => 'AB Bank PLC',
                'bank_routing_number' => '095000006',
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Inactive reserve account.',
            ],

            // ---- 4 MOBILE WALLETS ----
            [
                'code' => 'WALLET-BKASH-001',
                'swift_code' => null,
                'name' => 'bKash Merchant Wallet',
                'account_name' => 'bKash Collections',
                'is_active' => true,
                'type' => 'mobile',
                'card_type' => null,
                'account_number' => '01710000001',
                'bank_name' => 'bKash',
                'bank_routing_number' => null,
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'MFS collections channel.',
            ],
            [
                'code' => 'WALLET-NAGAD-001',
                'swift_code' => null,
                'name' => 'Nagad Merchant Wallet',
                'account_name' => 'Nagad Collections',
                'is_active' => true,
                'type' => 'mobile',
                'card_type' => null,
                'account_number' => '01810000001',
                'bank_name' => 'Nagad',
                'bank_routing_number' => null,
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Alternate MFS channel.',
            ],
            [
                'code' => 'WALLET-ROCKET-001',
                'swift_code' => null,
                'name' => 'Rocket Merchant Wallet',
                'account_name' => 'Rocket Collections',
                'is_active' => true,
                'type' => 'mobile',
                'card_type' => null,
                'account_number' => '01610000001',
                'bank_name' => 'Rocket (DBBL)',
                'bank_routing_number' => null,
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'DBBL Rocket MFS channel.',
            ],
            [
                'code' => 'WALLET-UPAY-001',
                'swift_code' => null,
                'name' => 'Upay Merchant Wallet',
                'account_name' => 'Upay Collections',
                'is_active' => true,
                'type' => 'mobile',
                'card_type' => null,
                'account_number' => '01910000001',
                'bank_name' => 'Upay (UCB)',
                'bank_routing_number' => null,
                'card_valid_from' => null,
                'card_expiry' => null,
                'card_cvv' => null,
                'card_pin' => null,
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'UCB Upay MFS channel.',
            ],

            // ---- 6 CARDS ----
            [
                'code' => 'CARD-VISA-001',
                'swift_code' => null,
                'name' => 'Visa Corporate Card',
                'account_name' => 'Visa Corp',
                'is_active' => true,
                'type' => 'card',
                'card_type' => 'visa',
                'account_number' => '4111111111111111',
                'bank_name' => 'BRAC Bank PLC',
                'bank_routing_number' => null,
                'card_valid_from' => '2023-01-01',
                'card_expiry' => '2027-12-31',
                'card_cvv' => '123',
                'card_pin' => '0000',
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Corporate expenses (demo).',
            ],
            [
                'code' => 'CARD-MASTER-001',
                'swift_code' => null,
                'name' => 'Mastercard Procurement Card',
                'account_name' => 'MC Procurement',
                'is_active' => true,
                'type' => 'card',
                'card_type' => 'mastercard',
                'account_number' => '5555555555554444',
                'bank_name' => 'The City Bank PLC',
                'bank_routing_number' => null,
                'card_valid_from' => '2022-06-01',
                'card_expiry' => '2026-05-31',
                'card_cvv' => '456',
                'card_pin' => '1234',
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Procurement (demo).',
            ],
            [
                'code' => 'CARD-AMEX-001',
                'swift_code' => null,
                'name' => 'AMEX Travel Card',
                'account_name' => 'AMEX Travel',
                'is_active' => true,
                'type' => 'card',
                'card_type' => 'amex',
                'account_number' => '371449635398431',
                'bank_name' => 'The City Bank PLC',
                'bank_routing_number' => null,
                'card_valid_from' => '2024-03-01',
                'card_expiry' => '2028-02-29',
                'card_cvv' => '999',
                'card_pin' => '5678',
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Travel (demo).',
            ],
            [
                'code' => 'CARD-UNIONPAY-001',
                'swift_code' => null,
                'name' => 'UnionPay Card',
                'account_name' => 'UPAY Card',
                'is_active' => true,
                'type' => 'card',
                'card_type' => 'unionpay',
                'account_number' => '6221260000000000',
                'bank_name' => 'Prime Bank PLC',
                'bank_routing_number' => null,
                'card_valid_from' => '2023-05-01',
                'card_expiry' => '2027-04-30',
                'card_cvv' => '321',
                'card_pin' => '4321',
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Domestic/international spend (demo).',
            ],
            [
                'code' => 'CARD-JCB-001',
                'swift_code' => null,
                'name' => 'JCB Corporate Card',
                'account_name' => 'JCB Corp',
                'is_active' => true,
                'type' => 'card',
                'card_type' => 'jcb',
                'account_number' => '3566002020360505',
                'bank_name' => 'Eastern Bank PLC',
                'bank_routing_number' => null,
                'card_valid_from' => '2022-10-01',
                'card_expiry' => '2026-09-30',
                'card_cvv' => '741',
                'card_pin' => '2468',
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'JCB network (demo).',
            ],
            [
                'code' => 'CARD-DISCOVER-001',
                'swift_code' => null,
                'name' => 'Discover Corporate Card',
                'account_name' => 'Discover Corp',
                'is_active' => true,
                'type' => 'card',
                'card_type' => 'discover',
                'account_number' => '6011000990139424',
                'bank_name' => 'AB Bank PLC',
                'bank_routing_number' => null,
                'card_valid_from' => '2023-02-01',
                'card_expiry' => '2027-01-31',
                'card_cvv' => '852',
                'card_pin' => '1357',
                'bank_iban' => null,
                'bank_address' => 'Dhaka, Bangladesh',
                'description' => 'Discover network (demo).',
            ],
        ];

        // Add timestamps and perform upsert on "code"
        $payload = array_map(function ($a) use ($now) {
            return array_merge($a, [
                'created_at' => $now,
                'updated_at' => $now,
            ]);
        }, $accounts);

        DB::table('accounts')->upsert(
            $payload,
            ['code'], // unique key
            [
                'swift_code',
                'name',
                'account_name',
                'is_active',
                'type',
                'card_type',
                'account_number',
                'bank_name',
                'bank_routing_number',
                'card_valid_from',
                'card_expiry',
                'card_cvv',
                'card_pin',
                'bank_iban',
                'bank_address',
                'description',
                'updated_at',
            ]
        );
    }
}
